# API Tests for Update Problem & Upload Files

### 1. Update Problem Metadata (PUT /problems/p/{slug})
PUT http://localhost:8080/problems/p/my-cool-problem
Content-Type: application/json
Authorization: Bearer mock-author-token

{
  "title": "My Super Cool Problem Updated",
  "timeLimit": 5000,
  "memoryLimit": 1024,
  "tags": ["dp", "math"]
}

### 2. Add Modifier
POST http://localhost:8080/problems/p/my-cool-problem/modifiers
Content-Type: application/json
Authorization: Bearer mock-author-token

{
  "userNickname": "modifier_nickname"
}

### 3. List Modifiers
GET http://localhost:8080/problems/p/my-cool-problem/modifiers
Authorization: Bearer mock-author-token

### 4. Remove Modifier
DELETE http://localhost:8080/problems/p/my-cool-problem/modifiers/modifier_nickname
Authorization: Bearer mock-author-token

