package group

const (
	ErrCodeInvalidName              = "INVALID_GROUP_NAME"
	ErrCodeReservedName             = "RESERVED_NAME"
	ErrCodeNameAlreadyExists        = "NAME_ALREADY_EXISTS"
	ErrCodeInvalidPolicyCombination = "INVALID_POLICY_COMBINATION"
	ErrCodeInsufficientPermissions  = "INSUFFICIENT_PERMISSIONS"
	ErrCodeGlobalGroupImmutable     = "GLOBAL_GROUP_IMMUTABLE"
	ErrCodeLastLead                 = "LAST_LEAD_CANNOT_BE_REMOVED"
	ErrCodeInvalidLeadAssignment    = "INVALID_LEAD_ASSIGNMENT"
	ErrCodeDuplicateUserInLists     = "DUPLICATE_USER_IN_LISTS"
	ErrCodeInvalidInitialMembers    = "INVALID_INITIAL_MEMBERS"
	ErrCodeForbiddenField           = "FORBIDDEN_FIELD"
	ErrCodeAlreadyMember            = "ALREADY_MEMBER"
	ErrCodeNotMember                = "NOT_MEMBER"
	ErrCodeGroupNotFound            = "GROUP_NOT_FOUND"
	ErrCodeInvalidJoinPolicy        = "INVALID_JOIN_POLICY"
	ErrCodeInvalidVisibility        = "INVALID_VISIBILITY"
	ErrCodeInvalidMemberRole        = "INVALID_MEMBER_ROLE"
	ErrCodeRoleUnchanged            = "ROLE_UNCHANGED"

	ErrCodeNicknameNotFound            = "NICKNAME_NOT_FOUND"
	ErrCodeCannotRemoveLastLead        = "CANNOT_REMOVE_LAST_LEAD"
	ErrCodeCannotRemoveFromGlobal      = "CANNOT_REMOVE_FROM_GLOBAL_GROUP"
	ErrCodeCannotRemoveAdminFromGlobal = "CANNOT_REMOVE_ADMIN_FROM_GLOBAL_GROUP"
	ErrCodeCannotLeaveGlobal           = "CANNOT_LEAVE_GLOBAL_GROUP"
	ErrCodeCannotLeaveAsLastLead       = "CANNOT_LEAVE_AS_LAST_LEAD"

	ErrCodeRequestAlreadyProcessed = "REQUEST_ALREADY_PROCESSED"
	ErrCodeRequestAlreadyPending   = "REQUEST_ALREADY_PENDING"
	ErrCodeRequestNotFound         = "REQUEST_NOT_FOUND"
	ErrCodeInvalidInviteToken      = "INVALID_INVITE_TOKEN"
	ErrCodeExpiredInviteToken      = "EXPIRED_INVITE_TOKEN"
)
